//---------------------------------------------------------
// Imports
//---------------------------------------------------------
import {IEndpointAttr} from 'types/endpoint';

//---------------------------------------------------------
// Dummy Data
//---------------------------------------------------------
export const dummyData: IEndpointAttr = {
	Attr: [
		{
			hostName: 'server-001',
			name: 'main-service',
			inactiveReTries: 3,
			probeType: 'HTTP',
			probeReq: 'GET /health',
			probeResp: '200 OK',
			probeDuration: 500,
			probePort: 8080,
			minDelay: '50ms',
			avgDelay: '120ms',
			maxDelay: '200ms',
			currState: 'active',
		},
		{
			hostName: 'server-002',
			name: 'auth-service',
			inactiveReTries: 5,
			probeType: 'TCP',
			probeReq: 'PING',
			probeResp: 'PONG',
			probeDuration: 300,
			probePort: 9000,
			minDelay: '30ms',
			avgDelay: '80ms',
			maxDelay: '150ms',
			currState: 'inactive',
		},
		{
			hostName: 'server-003',
			name: 'cache-service',
			inactiveReTries: 2,
			probeType: 'HTTP',
			probeReq: 'GET /status',
			probeResp: '200 OK',
			probeDuration: 200,
			probePort: 6379,
			minDelay: '20ms',
			avgDelay: '45ms',
			maxDelay: '100ms',
			currState: 'active',
		},
		{
			hostName: 'server-004',
			name: 'queue-service',
			inactiveReTries: 4,
			probeType: 'TCP',
			probeReq: 'STATUS',
			probeResp: 'RUNNING',
			probeDuration: 400,
			probePort: 5672,
			minDelay: '40ms',
			avgDelay: '90ms',
			maxDelay: '180ms',
			currState: 'active',
		},
		{
			hostName: 'server-005',
			name: 'storage-service',
			inactiveReTries: 3,
			probeType: 'HTTP',
			probeReq: 'GET /check',
			probeResp: '200 OK',
			probeDuration: 600,
			probePort: 7000,
			minDelay: '60ms',
			avgDelay: '150ms',
			maxDelay: '250ms',
			currState: 'active',
		},
		{
			hostName: 'server-006',
			name: 'logging-service',
			inactiveReTries: 2,
			probeType: 'UDP',
			probeReq: 'HEALTH',
			probeResp: 'OK',
			probeDuration: 250,
			probePort: 514,
			minDelay: '25ms',
			avgDelay: '60ms',
			maxDelay: '120ms',
			currState: 'active',
		},
		{
			hostName: 'server-007',
			name: 'metrics-service',
			inactiveReTries: 4,
			probeType: 'HTTP',
			probeReq: 'GET /metrics',
			probeResp: '200 OK',
			probeDuration: 350,
			probePort: 9090,
			minDelay: '35ms',
			avgDelay: '85ms',
			maxDelay: '160ms',
			currState: 'inactive',
		},
		{
			hostName: 'server-008',
			name: 'backup-service',
			inactiveReTries: 5,
			probeType: 'TCP',
			probeReq: 'CHECK',
			probeResp: 'ALIVE',
			probeDuration: 450,
			probePort: 8000,
			minDelay: '45ms',
			avgDelay: '100ms',
			maxDelay: '190ms',
			currState: 'active',
		},
		{
			hostName: 'server-009',
			name: 'search-service',
			inactiveReTries: 3,
			probeType: 'HTTP',
			probeReq: 'GET /ping',
			probeResp: '200 OK',
			probeDuration: 550,
			probePort: 9200,
			minDelay: '55ms',
			avgDelay: '130ms',
			maxDelay: '220ms',
			currState: 'active',
		},
		{
			hostName: 'server-010',
			name: 'api-gateway',
			inactiveReTries: 4,
			probeType: 'HTTP',
			probeReq: 'GET /health',
			probeResp: '200 OK',
			probeDuration: 280,
			probePort: 8888,
			minDelay: '28ms',
			avgDelay: '70ms',
			maxDelay: '140ms',
			currState: 'active',
		},
	],
};
