//---------------------------------------------------------
// Imports
//---------------------------------------------------------
import {IFirewallRules} from 'types/firewall';

//---------------------------------------------------------
// Dummy Data
//---------------------------------------------------------
export const dummyData: IFirewallRules = {
	fwAttr: [
		{
			ruleArguments: {
				sourceIP: '192.168.1.0/24',
				destinationIP: '10.0.0.0/16',
				minSourcePort: 1024,
				maxSourcePort: 65535,
				minDestinationPort: 80,
				maxDestinationPort: 80,
				protocol: 6,
				portName: 'eth0',
				preference: 100,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: true,
				allow: true,
				record: true,
				redirectPortName: 'http-alt',
				fwMark: 1,
				doSnat: true,
				toIP: '10.0.0.100',
				toPort: 8080,
				counter: '123:456',
				onDefault: true,
			},
		},
		{
			ruleArguments: {
				sourceIP: '0.0.0.0/0',
				destinationIP: '192.168.1.100',
				minSourcePort: 0,
				maxSourcePort: 65535,
				minDestinationPort: 22,
				maxDestinationPort: 22,
				protocol: 1,
				portName: 'eth1',
				preference: 50,
			},
			opts: {
				drop: true,
				trap: false,
				redirect: false,
				allow: false,
				record: true,
				redirectPortName: '',
				fwMark: 2,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '789:101',
				onDefault: false,
			},
		},
		{
			ruleArguments: {
				sourceIP: '172.16.0.0/16',
				destinationIP: '192.168.2.0/24',
				minSourcePort: 1024,
				maxSourcePort: 65535,
				minDestinationPort: 443,
				maxDestinationPort: 443,
				protocol: 132,
				portName: 'https',
				preference: 75,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: false,
				allow: true,
				record: true,
				redirectPortName: '',
				fwMark: 3,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '202:303',
				onDefault: true,
			},
		},
		{
			ruleArguments: {
				sourceIP: '192.168.3.0/24',
				destinationIP: '192.168.4.0/24',
				minSourcePort: 137,
				maxSourcePort: 139,
				minDestinationPort: 137,
				maxDestinationPort: 139,
				protocol: 17,
				portName: 'netbios',
				preference: 25,
			},
			opts: {
				drop: true,
				trap: true,
				redirect: false,
				allow: false,
				record: true,
				redirectPortName: '',
				fwMark: 4,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '404:505',
				onDefault: false,
			},
		},
		{
			ruleArguments: {
				sourceIP: '10.10.0.0/16',
				destinationIP: '10.20.0.0/16',
				minSourcePort: 1024,
				maxSourcePort: 65535,
				minDestinationPort: 3306,
				maxDestinationPort: 3306,
				protocol: 6,
				portName: 'mysql',
				preference: 80,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: true,
				allow: true,
				record: true,
				redirectPortName: 'mysql-proxy',
				fwMark: 5,
				doSnat: true,
				toIP: '10.20.0.10',
				toPort: 3307,
				counter: '606:707',
				onDefault: true,
			},
		},
		{
			ruleArguments: {
				sourceIP: '172.20.0.0/16',
				destinationIP: '172.30.0.0/16',
				minSourcePort: 1024,
				maxSourcePort: 65535,
				minDestinationPort: 5432,
				maxDestinationPort: 5432,
				protocol: 6,
				portName: 'test-device-1', // Test device name
				preference: 90,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: false,
				allow: true,
				record: true,
				redirectPortName: '',
				fwMark: 6,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '808:909',
				onDefault: false,
			},
		},
		{
			ruleArguments: {
				sourceIP: '192.168.10.0/24',
				destinationIP: '192.168.20.0/24',
				minSourcePort: 0,
				maxSourcePort: 65535,
				minDestinationPort: 8080,
				maxDestinationPort: 8080,
				protocol: 6,
				portName: 'test-device-1', // Same test device name
				preference: 95,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: false,
				allow: true,
				record: true,
				redirectPortName: '',
				fwMark: 7,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '111:222',
				onDefault: true,
			},
		},
		{
			ruleArguments: {
				sourceIP: '10.50.0.0/16',
				destinationIP: '10.60.0.0/16',
				minSourcePort: 1024,
				maxSourcePort: 65535,
				minDestinationPort: 27017,
				maxDestinationPort: 27017,
				protocol: 1,
				portName: 'test-device-2', // Another test device
				preference: 85,
			},
			opts: {
				drop: false,
				trap: false,
				redirect: false,
				allow: true,
				record: true,
				redirectPortName: '',
				fwMark: 8,
				doSnat: false,
				toIP: '',
				toPort: 0,
				counter: '333:444',
				onDefault: false,
			},
		},
	],
};
