//---------------------------------------------------------
// Imports
//---------------------------------------------------------
import {IInstance} from 'types/oam';

//---------------------------------------------------------
// Dummy Data
//---------------------------------------------------------
export const dummyData: IInstance[] = [
	{
		api_endpoint: '/api/v1/instance1',
		cimage: 'ubuntu:20.04',
		created_at: '2024-01-15T09:00:00Z',
		ctag: 'prod',
		description:
			'Production server instance 1 Production server instance 1 Production server instance 1 Production server instance 1 Production server instance 1 Production server instance 1',
		host: 'server1.example.com',
		id: 1,
		is_active: true,
		name: 'Instance-01',
		port: '8080',
		protocol: 'https',
		version: '1.0.0',
	},
	{
		api_endpoint: '/api/v1/instance2',
		cimage: 'debian:11',
		created_at: '2024-01-16T10:30:00Z',
		ctag: 'dev',
		description: 'Development server instance 2',
		host: 'server2.example.com',
		id: 2,
		is_active: false,
		name: 'Instance-02',
		port: '8080',
		protocol: 'https',
		version: '1.1.0',
	},
	{
		api_endpoint: '/api/v1/instance3',
		cimage: 'alpine:3.15',
		created_at: '2024-01-17T11:45:00Z',
		ctag: 'test',
		description: 'Test server instance 3',
		host: 'server3.example.com',
		id: 3,
		is_active: true,
		name: 'Instance-03',
		port: '8080',
		protocol: 'https',
		version: '1.0.5',
	},
	{
		api_endpoint: '/api/v1/instance4',
		cimage: 'ubuntu:22.04',
		created_at: '2024-01-18T13:15:00Z',
		ctag: 'prod',
		description: 'Production server instance 4',
		host: 'server4.example.com',
		id: 4,
		is_active: true,
		name: 'Instance-04',
		port: '8080',
		protocol: 'https',
		version: '2.0.0',
	},
	{
		api_endpoint: '/api/v1/instance5',
		cimage: 'debian:12',
		created_at: '2024-01-19T14:20:00Z',
		ctag: 'staging',
		description: 'Staging server instance 5',
		host: 'server5.example.com',
		id: 5,
		is_active: false,
		name: 'Instance-05',
		port: '8080',
		protocol: 'https',
		version: '1.2.0',
	},
	{
		api_endpoint: '/api/v1/instance6',
		cimage: 'alpine:3.16',
		created_at: '2024-01-20T15:45:00Z',
		ctag: 'dev',
		description: 'Development server instance 6',
		host: 'server6.example.com',
		id: 6,
		is_active: true,
		name: 'Instance-06',
		port: '8080',
		protocol: 'https',
		version: '1.3.0',
	},
	{
		api_endpoint: '/api/v1/instance7',
		cimage: 'ubuntu:21.04',
		created_at: '2024-01-21T16:30:00Z',
		ctag: 'test',
		description: 'Test server instance 7',
		host: 'server7.example.com',
		id: 7,
		is_active: false,
		name: 'Instance-07',
		port: '8080',
		protocol: 'https',
		version: '1.1.5',
	},
	{
		api_endpoint: '/api/v1/instance8',
		cimage: 'debian:10',
		created_at: '2024-01-22T17:10:00Z',
		ctag: 'prod',
		description: 'Production server instance 8',
		host: 'server8.example.com',
		id: 8,
		is_active: true,
		name: 'Instance-08',
		port: '8080',
		protocol: 'https',
		version: '2.1.0',
	},
	{
		api_endpoint: '/api/v1/instance9',
		cimage: 'alpine:3.14',
		created_at: '2024-01-23T18:25:00Z',
		ctag: 'staging',
		description: 'Staging server instance 9',
		host: 'server9.example.com',
		id: 9,
		is_active: true,
		name: 'Instance-09',
		port: '8080',
		protocol: 'https',
		version: '1.4.0',
	},
	{
		api_endpoint: '/api/v1/instance10',
		cimage: 'ubuntu:22.10',
		created_at: '2024-01-24T19:40:00Z',
		ctag: 'dev',
		description: 'Development server instance 10',
		host: 'server10.example.com',
		id: 10,
		is_active: false,
		name: 'Instance-10',
		port: '8080',
		protocol: 'https',
		version: '1.5.0',
	},
];
