//---------------------------------------------------------
// Imports
//---------------------------------------------------------
import {IPortInfo} from 'types/port';

//---------------------------------------------------------
// Dummy Data
//---------------------------------------------------------
export const dummyData: IPortInfo = {
	portAttr: [
		{
			portName: 'http',
			portNo: 0,
			zone: 'external',
			portSoftwareInformation: {
				osId: 1,
				portType: 1,
				portProp: 1,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x44],
				macAddress: '00:1B:44:11:3A:B7',
				mtu: 1500,
				link: true,
				state: true,
				master: 'bridge0',
				real: 'eth0',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 1024,
				txBytes: 2048,
				rxPackets: 100,
				txPackets: 200,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.1.1'],
				IPv6Address: ['fe80::1'],
			},
			portL2Information: {
				isPvid: true,
				vid: 1,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth1',
			portNo: 1,
			zone: 'internal',
			portSoftwareInformation: {
				osId: 2,
				portType: 1,
				portProp: 2,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x45],
				macAddress: '00:1B:45:22:3B:C8',
				mtu: 1500,
				link: true,
				state: true,
				master: 'bridge0',
				real: 'eth1',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 4096,
				txBytes: 8192,
				rxPackets: 300,
				txPackets: 400,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.2.1'],
				IPv6Address: ['fe80::2'],
			},
			portL2Information: {
				isPvid: false,
				vid: 2,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth2',
			portNo: 2,
			zone: 'dmz',
			portSoftwareInformation: {
				osId: 3,
				portType: 2,
				portProp: 1,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x46],
				macAddress: '00:1B:46:33:3C:D9',
				mtu: 1500,
				link: true,
				state: true,
				master: 'bridge1',
				real: 'eth2',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 16384,
				txBytes: 32768,
				rxPackets: 500,
				txPackets: 600,
				rxErrors: 1,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.3.1'],
				IPv6Address: ['fe80::3'],
			},
			portL2Information: {
				isPvid: true,
				vid: 3,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth3',
			portNo: 3,
			zone: 'guest',
			portSoftwareInformation: {
				osId: 4,
				portType: 1,
				portProp: 2,
				portActive: true,
				bpfLoaded: false,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x47],
				macAddress: '00:1B:47:44:3D:E0',
				mtu: 1500,
				link: true,
				state: true,
				master: 'bridge1',
				real: 'eth3',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 65536,
				txBytes: 131072,
				rxPackets: 700,
				txPackets: 800,
				rxErrors: 0,
				txErrors: 1,
			},
			portL3Information: {
				routed: false,
				IPv4Address: ['192.168.4.1'],
				IPv6Address: ['fe80::4'],
			},
			portL2Information: {
				isPvid: false,
				vid: 4,
			},
			DataplaneSync: 0,
		},
		{
			portName: 'eth4',
			portNo: 4,
			zone: 'management',
			portSoftwareInformation: {
				osId: 5,
				portType: 2,
				portProp: 1,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x48],
				macAddress: '00:1B:48:55:3E:F1',
				mtu: 9000,
				link: true,
				state: true,
				master: 'bridge2',
				real: 'eth4',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 262144,
				txBytes: 524288,
				rxPackets: 900,
				txPackets: 1000,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.5.1'],
				IPv6Address: ['fe80::5'],
			},
			portL2Information: {
				isPvid: true,
				vid: 5,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth5',
			portNo: 5,
			zone: 'backup',
			portSoftwareInformation: {
				osId: 6,
				portType: 1,
				portProp: 2,
				portActive: false,
				bpfLoaded: false,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x49],
				macAddress: '00:1B:49:66:3F:G2',
				mtu: 1500,
				link: false,
				state: false,
				master: 'bridge2',
				real: 'eth5',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 0,
				txBytes: 0,
				rxPackets: 0,
				txPackets: 0,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: false,
				IPv4Address: ['192.168.6.1'],
				IPv6Address: ['fe80::6'],
			},
			portL2Information: {
				isPvid: false,
				vid: 6,
			},
			DataplaneSync: 0,
		},
		{
			portName: 'eth6',
			portNo: 6,
			zone: 'storage',
			portSoftwareInformation: {
				osId: 7,
				portType: 2,
				portProp: 1,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x4a],
				macAddress: '00:1B:4A:77:40:H3',
				mtu: 9000,
				link: true,
				state: true,
				master: 'bridge3',
				real: 'eth6',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 1048576,
				txBytes: 2097152,
				rxPackets: 1100,
				txPackets: 1200,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.7.1'],
				IPv6Address: ['fe80::7'],
			},
			portL2Information: {
				isPvid: true,
				vid: 7,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth7',
			portNo: 7,
			zone: 'cluster',
			portSoftwareInformation: {
				osId: 8,
				portType: 2,
				portProp: 2,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x4b],
				macAddress: '00:1B:4B:88:41:I4',
				mtu: 9000,
				link: true,
				state: true,
				master: 'bridge3',
				real: 'eth7',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 4194304,
				txBytes: 8388608,
				rxPackets: 1300,
				txPackets: 1400,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.8.1'],
				IPv6Address: ['fe80::8'],
			},
			portL2Information: {
				isPvid: true,
				vid: 8,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth8',
			portNo: 8,
			zone: 'monitoring',
			portSoftwareInformation: {
				osId: 9,
				portType: 1,
				portProp: 1,
				portActive: true,
				bpfLoaded: true,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x4c],
				macAddress: '00:1B:4C:99:42:J5',
				mtu: 1500,
				link: true,
				state: true,
				master: 'bridge4',
				real: 'eth8',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 16777216,
				txBytes: 33554432,
				rxPackets: 1500,
				txPackets: 1600,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: true,
				IPv4Address: ['192.168.9.1'],
				IPv6Address: ['fe80::9'],
			},
			portL2Information: {
				isPvid: false,
				vid: 9,
			},
			DataplaneSync: 1,
		},
		{
			portName: 'eth9',
			portNo: 9,
			zone: 'backup',
			portSoftwareInformation: {
				osId: 10,
				portType: 1,
				portProp: 2,
				portActive: false,
				bpfLoaded: false,
			},
			portHardwareInformation: {
				rawMacAddress: [0x00, 0x1b, 0x4d],
				macAddress: '00:1B:4D:AA:43:K6',
				mtu: 1500,
				link: false,
				state: false,
				master: 'bridge4',
				real: 'eth9',
				tunnelId: 0,
			},
			portStatisticInformation: {
				rxBytes: 0,
				txBytes: 0,
				rxPackets: 0,
				txPackets: 0,
				rxErrors: 0,
				txErrors: 0,
			},
			portL3Information: {
				routed: false,
				IPv4Address: ['192.168.10.1'],
				IPv6Address: ['fe80::10'],
			},
			portL2Information: {
				isPvid: false,
				vid: 10,
			},
			DataplaneSync: 0,
		},
	],
};
