apiVersion: v1
kind: Service
metadata:
  name: loxilb-ui-service
  namespace: loxilb-system
  labels:
    app: loxilb-ui
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    # service.beta.kubernetes.io/azure-load-balancer-type: "nlb"  # For Azure
    # cloud.google.com/load-balancer-type: "Internal"  # For GCP
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: loxilb-ui
    component: frontend
  sessionAffinity: None