//---------------------------------------------------------
// LX-CONTRACT — the UI must stay inside upstream loxilb's swagger.
//
// This is the backward-compatibility spec the other loxilb specs lean on.
// Instead of asserting page-by-page that some control is hidden, it watches
// every request the browser sends to a loxilb instance and fails on anything
// `api-spec/loxilb-swagger.yml` does not declare — with the generated
// capability map (gateway spec MINUS loxilb spec) as the oracle.
//
// Why that matters more than a response check: gateway-only BODY FIELDS are
// accepted by loxilb with 200 and silently dropped (go-swagger's default for
// unknown properties). The operator sees a green Success popup and the config
// never took effect. Only the request side can catch it. Verified live on
// 0.9.8-dev: POST with model_name/path_prefix → {"result":"Success"}, and
// both fields absent on read-back.
//
// The oracle is regenerated by `npm run gen:api`, so re-vendoring either
// swagger automatically re-aims these assertions — nothing here is a
// hand-maintained list of gateway features.
//
// Sibling coverage: gating.spec.ts asserts the UI CONTROLS are gone (the
// cause); this spec asserts nothing gateway-only leaves the browser (the
// effect). Both are needed — a hidden control still ships a bug if some
// other code path sends the field anyway.
//---------------------------------------------------------
import {expect, test} from '../../fixtures';
import {activeInstance, gw, OAM_BASE, sweepFirewallRules, sweepLbRules} from '../../helpers/api';
import {dialog, dialogButton, expectSuccessAndDismiss, openToolbarDialog} from '../../helpers/dialogs';
import {expandSection, field} from '../../helpers/form';
import {refreshUntilRow, selectRowByText, showAllRows, toolbarButton} from '../../helpers/table';
import {attachContractGuard, capabilityMap, formatViolations} from '../../helpers/loxilb-contract';
import {gotoLoxilbPage, requireLoxilbInstance, SHARED_PAGES} from '../_loxilb';

const LB_PATH = '/config/loadbalancer';
const VIP = '203.0.113.60';
const EP_IP = '203.0.113.61';
const LB_NAME = 'e2e-lx-contract';
// Keep the listener away from common host/OAM ports. The live OSS deployment
// correctly rejects a VIP on any OAM_RESERVED_ENDPOINTS listener.
const LB_PORT = '18060';

let instName: string;

test.describe('@loxilb LX-CONTRACT — no gateway-only API surface reaches a loxilb instance', () => {
	test.beforeAll(async () => {
		instName = await requireLoxilbInstance();
	});

	test.afterEach(async () => {
		await sweepLbRules();
		await sweepFirewallRules();
	});

	//---------------------------------------------------------
	// LX-CONTRACT-0 — the guard itself
	//---------------------------------------------------------
	// A contract guard that matches nothing passes every test for the wrong
	// reason. Before trusting a green result anywhere below, prove the oracle
	// is loaded and the matcher fires on a request that IS a violation.
	test('LX-CONTRACT-0: the guard detects a gateway-only request (self-test)', async ({page, consoleGuard}) => {
		const map = capabilityMap();
		expect(map.gatewayOnlyPaths.length, 'capability map has gateway-only paths').toBeGreaterThan(0);
		expect(Object.keys(map.gatewayOnlyEnumValues).length, 'capability map has gateway-only enum sites').toBeGreaterThan(0);
		expect(map.gatewayOnlyFields['LoadbalanceEntry.serviceArguments']?.length, 'capability map has gateway-only serviceArguments').toBeGreaterThan(0);

		const guard = await attachContractGuard(page);
		await gotoLoxilbPage(page, 'traffic/lb', instName);
		guard.reset();

		const inst = await activeInstance();
		const base = `${OAM_BASE}/loxilbs/${inst.id}/netlox/v1`;
		// Deliberate violations, fired from the page so they travel the same
		// path a real UI request would. Unauthenticated (401) / rejected —
		// the guard records the REQUEST, which is the whole point.
		consoleGuard.allow(/Failed to load resource/i);
		await page.evaluate(async ({base}) => {
			await fetch(`${base}/config/ipfilter/all`).catch(() => undefined);
			await fetch(`${base}/config/loadbalancer`, {
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({serviceArguments: {name: 'guard-selftest', sel: 8, model_name: 'llama'}, endpoints: []}),
			}).catch(() => undefined);
		}, {base});
		await page.waitForTimeout(500); // let the request events drain

		const kinds = guard.violations().map(v => v.kind);
		expect(kinds, `guard must flag the gateway-only path\n${formatViolations(guard.violations())}`).toContain('path');
		expect(kinds, `guard must flag the gateway-only enum value\n${formatViolations(guard.violations())}`).toContain('enum');
		expect(kinds, `guard must flag the gateway-only body field\n${formatViolations(guard.violations())}`).toContain('field');
	});

	//---------------------------------------------------------
	// LX-CONTRACT-1 — read paths
	//---------------------------------------------------------
	test('LX-CONTRACT-1: browsing every shared page sends nothing outside the loxilb spec', async ({page, consoleGuard}) => {
		// loxilb's /status/device is shell-exec based and 500s transiently
		// (200 on re-probe); the cards degrade in-page. Not a contract failure.
		consoleGuard.allow(/Failed to load resource.*50\d/i);

		const guard = await attachContractGuard(page);
		await gotoLoxilbPage(page, 'dashboard', instName);
		// Everything before this point was fetched while the /version probe was
		// still in flight and gating was permissive by design — only what the
		// UI sends with a RESOLVED loxilb flavor is in scope.
		guard.reset();

		for (const route of SHARED_PAGES) {
			await gotoLoxilbPage(page, route, instName);
			// Let the page's queries (and the dashboard's 1s poll) actually fire.
			await page.waitForTimeout(1500);
		}

		expect(guard.seen().length, 'the walk must actually have hit the instance API').toBeGreaterThan(SHARED_PAGES.length);
		expect(guard.unexpected(), `gateway-only API surface sent to a loxilb instance:\n${formatViolations(guard.unexpected())}`).toEqual([]);
	});

	//---------------------------------------------------------
	// LX-CONTRACT-2 — write paths (the silent-drop class)
	//---------------------------------------------------------
	test('LX-CONTRACT-2: the LB create/edit/delete round-trip sends nothing outside the loxilb spec', async ({page}) => {
		const guard = await attachContractGuard(page);
		await gotoLoxilbPage(page, 'traffic/lb', instName);
		guard.reset();

		// LX-EP-DEFAULTS was waived here until 2026-08-18. EndpointListForm.handleAdd
		// still seeds `ep_role: 0, nixl_port: 0` on every new row — it has to, or
		// the P/D dropdown's announce path deletes the row the user just added —
		// but the connector now projects outgoing bodies onto the fields the
		// target flavor declares (`projectOntoFlavor` in
		// connector/instance/load_balancer.ts), so the seeds no longer reach the
		// wire. The waiver is gone; this test asserts the payload unaided again.
		await expect(toolbarButton(page, 'Add')).toBeVisible({timeout: 20_000});
		await showAllRows(page);

		// Create — the full form, every accordion opened, so any gateway-only
		// control that survived the flavor gate would be filled and sent.
		await openToolbarDialog(page, 'Add', 'Add Load Balancer Rule');
		await field(page, 'Rule Name').fill(LB_NAME);
		await expandSection(page, /^Basic Settings/);
		await field(page, 'External IP').fill(VIP);
		await field(page, 'Port Min').fill(LB_PORT);
		await expandSection(page, /^Advanced Settings/);
		const eps = await expandSection(page, /^Endpoints$/);
		await eps.getByRole('button', {name: 'Add', exact: true}).click();
		await field(page, 'IP', eps).nth(0).fill(EP_IP);
		await field(page, 'Target Port', eps).nth(0).fill(LB_PORT);
		await page.mouse.move(0, 0); // drop any sticky accordion tooltip
		const [createReq] = await Promise.all([
			page.waitForRequest(r => r.method() === 'POST' && r.url().includes(LB_PATH)),
			dialogButton(page, 'Create').click(),
		]);
		expect((await createReq.response())?.status(), 'loxilb accepted the create').toBeLessThan(300);
		await expectSuccessAndDismiss(page);
		await refreshUntilRow(page, LB_NAME);

		// Edit — the path that most easily leaks gateway-only fields, because the
		// dialog reloads a persisted rule and (on loxilb, which has no PATCH)
		// re-sends the WHOLE body as an upsert.
		await selectRowByText(page, LB_NAME);
		await openToolbarDialog(page, 'Mode', 'Edit Load Balancer Rule'); // edit (pencil)
		await expandSection(page, /^Advanced Settings/);
		await field(page, 'Inactive Timeout').fill('120');
		await page.mouse.move(0, 0);
		await dialogButton(page, 'Update').click();
		await expect(dialog(page).getByText('Load balancer rule updated successfully.')).toBeVisible();
		await dialogButton(page, 'OK').click();

		expect(guard.unexpected(), `gateway-only API surface sent while creating/editing an LB rule on loxilb:\n${formatViolations(guard.unexpected())}`).toEqual([]);

		// The write really landed — a guard that saw no violations because the
		// UI sent nothing at all would be worthless.
		const readback = await gw('GET', `${LB_PATH}/all`);
		const rules = (await readback.json()).lbAttr ?? [];
		expect(rules.some((r: any) => r.serviceArguments?.name === LB_NAME), 'rule persisted on loxilb').toBe(true);
	});
});
